import type { RemediationContext } from "./remediationLab";

function htmlEscape(value: string) {
  return value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#039;");
}

export function buildRemediationEvidenceHtml(context: RemediationContext, generatedAt = new Date().toISOString()) {
  const { finding } = context;
  const rows = [
    ["Finding", `${finding.algorithm} · ${finding.cryptoRole}`],
    ["Asset", finding.assetName],
    ["Location", finding.sourceLocation],
    ["Severity", `${finding.riskLevel} · ${context.riskScore}/100`],
    ["Recommendation", context.candidate],
    ["Workspace", context.workspaceId],
    ["Scope", "Browser-local demonstration fixture; no source, secret, network, or production system accessed."],
  ];
  const table = rows.map(([label, value]) => `<tr><th>${htmlEscape(label)}</th><td>${htmlEscape(value)}</td></tr>`).join("");
  const plan = context.migrationPlan.map((step, index) => `<li><strong>${htmlEscape(`Step ${index + 1}: ${step.title}`)}</strong><span>${htmlEscape(step.description)}</span></li>`).join("");
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>ECDAT evidence — ${htmlEscape(context.workspaceId)}</title><style>body{margin:0;background:#060606;color:#e5e7eb;font-family:Inter,ui-sans-serif,system-ui,sans-serif;line-height:1.55}.page{max-width:860px;margin:0 auto;padding:48px 28px 72px}.eyebrow{color:#67e8f9;font:600 11px ui-monospace,SFMono-Regular,monospace;letter-spacing:.14em;text-transform:uppercase}.hero{border:1px solid #334155;border-radius:20px;padding:28px;background:linear-gradient(135deg,#0b1725,#081321)}h1{margin:8px 0;font-size:34px;color:#fff}h2{margin:32px 0 12px;font-size:19px;color:#fff}.note{border-left:3px solid #67e8f9;background:#0b1b2b;padding:14px 16px;border-radius:0 12px 12px 0;color:#cbd5e1}table{width:100%;border-collapse:separate;border-spacing:0;overflow:hidden;border:1px solid #334155;border-radius:14px;background:#0b111a}th,td{padding:13px 16px;border-bottom:1px solid #263244;text-align:left;vertical-align:top}th{width:31%;color:#94a3b8;font-size:12px;text-transform:uppercase;letter-spacing:.08em}td{color:#f1f5f9}tr:last-child th,tr:last-child td{border-bottom:0}ol{margin:0;padding-left:23px}li{margin:10px 0;padding:12px;border:1px solid #263244;border-radius:12px;background:#0b111a}li strong,li span{display:block}li span{margin-top:4px;color:#cbd5e1;font-size:14px}.footer{margin-top:36px;color:#94a3b8;font-size:12px}</style></head><body><main class="page"><section class="hero"><p class="eyebrow">ECDAT remediation evidence</p><h1>Remediation Lab export</h1><p>Evidence → Change → Proof · Generated ${htmlEscape(generatedAt)}</p></section><h2>Finding context</h2><table>${table}</table><h2>Migration plan</h2><ol>${plan}</ol><h2>Safety boundary</h2><p class="note">This report is a browser-local evidence fixture generated by the ECDAT Remediation Lab. It does not represent a production change, validation result, or deployed configuration.</p><p class="footer">ECDAT · Cryptographic intelligence · Workspace ${htmlEscape(context.workspaceId)}</p></main></body></html>`;
}

export function invokeEvidencePdfExport(print: () => void) {
  print();
}
