import { Check, ChevronRight, Network, ShieldCheck } from "lucide-react";
import { useState } from "react";

const stages = [
  { id: "classical", name: "Classical", detail: "ECDH / existing public-key boundary", note: "Current observed estate", tone: "border-rose-200/20 bg-rose-300/[0.05] text-rose-100" },
  { id: "hybrid", name: "Hybrid", detail: "Existing boundary + ML-KEM-768", note: "Interoperability validation path", tone: "border-amber-200/25 bg-amber-200/[0.06] text-amber-100" },
  { id: "pqc", name: "PQC target", detail: "ML-KEM-768 enabled boundary", note: "Subject to provider validation", tone: "border-emerald-200/20 bg-emerald-300/[0.05] text-emerald-100" },
] as const;

export function HybridDemo() {
  const [selected, setSelected] = useState<(typeof stages)[number]["id"]>("hybrid");
  const active = stages.find(stage => stage.id === selected) ?? stages[1];
  return <section className="rounded-3xl border border-amber-200/15 bg-[#091423] p-5 shadow-2xl shadow-black/15 md:p-6"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-amber-100">Transition architecture</p><h2 className="mt-3 font-display text-2xl font-semibold tracking-[-.035em] text-white">Classical → hybrid → PQC planning view</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">An illustrative migration sequence derived from protocol-boundary guidance. It is not a live network handshake or a claim that a protocol is currently hybrid-ready.</p><div className="mt-6 grid gap-3 lg:grid-cols-[1fr_auto_1fr_auto_1fr] lg:items-stretch">{stages.flatMap((stage, index) => [<button type="button" key={stage.id} onClick={() => setSelected(stage.id)} aria-pressed={selected === stage.id} className={`rounded-2xl border p-4 text-left transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-amber-200/60 ${selected === stage.id ? stage.tone : "border-white/[0.08] bg-[#06101c]/65 text-slate-400 hover:border-white/15"}`}><span className="text-[10px] font-bold uppercase tracking-[.16em]">0{index + 1}</span><p className="mt-3 text-base font-semibold text-slate-100">{stage.name}</p><p className="mt-2 text-xs leading-5">{stage.detail}</p><p className="mt-4 text-[10px] font-medium uppercase tracking-[.12em] opacity-80">{stage.note}</p></button>, index < stages.length - 1 ? <div key={`${stage.id}-arrow`} className="hidden place-items-center lg:grid"><ChevronRight className="h-5 w-5 text-amber-100/70" /></div> : null])}</div><div className="mt-5 flex gap-3 rounded-2xl border border-white/[0.08] bg-[#06101c]/70 p-4"><Network className="mt-0.5 h-5 w-5 shrink-0 text-amber-100" /><div><p className="flex items-center gap-2 text-sm font-semibold text-slate-100"><ShieldCheck className="h-4 w-4 text-emerald-200" />Selected posture: {active.name}</p><p className="mt-1 text-xs leading-5 text-slate-500">{active.detail}. Confirm peer support, provider behavior, message size, telemetry, and rollback before a production transition.</p></div><Check className="ml-auto h-4 w-4 shrink-0 text-emerald-200" /></div></section>;
}
