import { Button } from "@/components/ui/button";
import { runMlDsaDemo, type MlDsaDemoOutcome } from "@/lib/pqcDemo";
import { FileSignature, Play, ShieldAlert, ShieldCheck } from "lucide-react";
import { useState } from "react";

export function MlDsaDemo() {
  const [message, setMessage] = useState("Treasury approval — PQC demonstration");
  const [outcome, setOutcome] = useState<MlDsaDemoOutcome | null>(null);
  const [error, setError] = useState<string | null>(null);
  const run = () => { try { setError(null); setOutcome(runMlDsaDemo(message.trim() || "ECDAT demonstration")); } catch { setError("The browser could not run the isolated ML-DSA demonstration. Retry in a current browser with secure randomness available."); } };
  return <section className="rounded-3xl border border-violet-200/15 bg-[#091423] p-5 shadow-2xl shadow-black/15 md:p-6"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-violet-200">FIPS 204 · ML-DSA-65</p><h2 className="mt-3 font-display text-2xl font-semibold tracking-[-.035em] text-white">Digital-signature demonstration</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">A local signing and altered-message verification exercise. Private keys and signatures are summarized in memory only and never leave this browser.</p><div className="mt-6 grid gap-4 lg:grid-cols-[1fr_0.9fr]"><div><label className="text-[10px] font-bold uppercase tracking-[.16em] text-slate-500" htmlFor="pqc-demo-message">Demonstration message</label><textarea id="pqc-demo-message" value={message} onChange={event => setMessage(event.target.value)} rows={4} className="mt-2 w-full resize-none rounded-2xl border border-white/10 bg-[#06101c] p-3 text-sm text-slate-100 outline-none transition focus:border-violet-200/35" /><Button onClick={run} className="mt-3 bg-violet-300 text-[#160e2f] hover:bg-violet-200"><Play className="h-3.5 w-3.5 fill-current" />Sign and verify</Button></div><div className="space-y-3">{[[FileSignature, "Signature", outcome ? `${outcome.signatureBytes.toLocaleString()} bytes produced locally` : "Generate a local detached signature"], [ShieldCheck, "Verification", outcome?.signatureValid ? "VALID — original message verified" : "Verify the original message"], [ShieldAlert, "Tamper test", outcome?.tamperDetected ? "INVALID — altered message correctly rejected" : "Attempt verification after altering the message"]].map(([Icon, title, note]) => { const VisualIcon = Icon as typeof FileSignature; return <div key={String(title)} className="flex gap-3 rounded-2xl border border-white/[0.08] bg-[#06101c]/70 p-3"><VisualIcon className={`mt-0.5 h-4 w-4 shrink-0 ${title === "Tamper test" ? "text-rose-200" : "text-violet-200"}`} /><div><p className="text-sm font-semibold text-slate-100">{String(title)}</p><p className="mt-1 text-xs leading-5 text-slate-500">{String(note)}</p></div></div>; })}</div></div>{error ? <p role="alert" className="mt-4 text-xs text-rose-200">{error}</p> : null}</section>;
}
