import { Breadcrumb, EcdatHeader } from "@/components/EcdatHeader";
import { WorkspaceState } from "@/components/WorkspaceState";
import { Badge } from "@/components/ui/badge";
import { useActiveEcdatScan } from "@/hooks/useActiveEcdatScan";
import { roadmapFindingFromSearch, summarizeIndicativeEffort } from "@/lib/roadmapInsights";
import { ArrowDown, Boxes, CheckCircle2, GitMerge, Route, Timer } from "lucide-react";

export default function Roadmap() {
  const workspace = useActiveEcdatScan();
  const { waves } = workspace;
  const effort = summarizeIndicativeEffort(waves);
  const findingKey = typeof window === "undefined" ? null : roadmapFindingFromSearch(window.location.search);
  const findingContext = workspace.findings.find(finding => finding.findingKey === findingKey);
  if (workspace.hasError) return <WorkspaceState state="error" title="Migration roadmap is unavailable" description="The active scan could not be used to derive remediation waves." onRetry={() => void workspace.retry()} />;
  if (workspace.isLoading && !waves.length) return <WorkspaceState state="loading" title="Building migration waves" description="Ordering remediation work by risk, shared dependencies, and delivery constraints." />;
  if (!waves.length) return <WorkspaceState state="empty" title="No migration waves yet" description="Run a seeded scan to derive dependency-aware remediation work." />;
  return <div className="mx-auto max-w-[1550px]"><Breadcrumb section="Migration roadmap" /><EcdatHeader eyebrow="Dependency-aware action plan" title="Migrate in waves, not in a panic." description="Remediation groups work by immediate weakness, shared cryptographic dependencies, and quantum-vulnerable boundaries so the highest-leverage changes happen first." /><div className="mt-5 flex flex-wrap items-center gap-2"><Badge variant="outline" className="border-cyan-200/20 bg-cyan-300/[0.05] text-cyan-100">{workspace.usingSavedScan ? "Saved scan roadmap" : "Seeded scenario roadmap"}</Badge>{findingContext ? <Badge variant="outline" className="border-amber-200/20 bg-amber-300/[0.06] text-amber-100">Planning context: {findingContext.algorithm} · {findingContext.assetName}</Badge> : null}<span className="text-xs text-slate-500">Active context: {workspace.displayName}</span></div>
    <div className="mt-4 grid gap-5 xl:grid-cols-[1fr_0.38fr]"><section className="space-y-3">{waves.map((wave, index) => <div key={wave.wave} className="relative rounded-3xl border border-white/8 bg-[#091423] p-5 md:p-6"><div className="flex flex-col gap-4 md:flex-row md:items-start"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-cyan-300/10 font-display text-xl font-semibold text-cyan-100">0{wave.wave}</div><div className="flex-1"><div className="flex flex-wrap items-start justify-between gap-2"><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-display text-xl font-semibold tracking-[-0.03em] text-white">{wave.title}</h2><Badge variant="outline" className={index === 0 ? "border-emerald-200/20 bg-emerald-300/[0.05] text-emerald-100" : "border-white/10 text-slate-400"}>{index === 0 ? "First sequencing gate" : `Follows wave ${waves[index - 1]?.wave}`}</Badge></div><p className="mt-1 max-w-2xl text-sm leading-6 text-slate-400">{wave.rationale}</p></div><Badge variant="outline" className="border-amber-200/15 bg-amber-200/[0.04] text-amber-100">{wave.indicativeEffort}</Badge></div><div className="mt-5 h-1.5 overflow-hidden rounded-full bg-white/5"><div className="h-full rounded-full bg-gradient-to-r from-cyan-300 to-emerald-300" style={{ width: `${((index + 1) / waves.length) * 100}%` }} /></div><div className="mt-5 grid gap-3 md:grid-cols-2"><RoadmapDetail icon={Boxes} label="Scope" text={wave.scope} /><RoadmapDetail icon={GitMerge} label="Dependency gate" text={wave.dependencies} /></div></div></div>{index < waves.length - 1 ? <ArrowDown className="absolute -bottom-5 left-5 z-10 h-5 w-5 rounded-full bg-[#06101c] p-1 text-cyan-200" /> : null}</div>)}</section>
      <aside className="space-y-5"><section className="rounded-3xl border border-white/8 bg-[#091423] p-5"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-emerald-300/10 text-emerald-100"><Route className="h-4 w-4" /></span><div><p className="text-sm font-medium text-slate-100">Sequencing summary</p><p className="text-xs text-slate-500">Active dependency-aware path</p></div></div><div className="mt-5 rounded-2xl border border-cyan-200/10 bg-cyan-300/[0.04] p-4"><p className="flex items-center gap-2 text-xs font-medium text-cyan-100"><Timer className="h-4 w-4" />Indicative aggregate effort</p><p className="mt-2 font-display text-2xl text-white">{effort.parsedWaves ? `${effort.minimum}–${effort.maximum}` : "Not parsed"}</p><p className="mt-1 text-xs text-slate-500">{effort.parsedWaves ? `engineer-weeks across ${effort.parsedWaves} labelled waves` : "Wave labels do not expose a comparable effort range."}</p></div><p className="mt-4 text-xs leading-5 text-slate-500">This is a simple sum of displayed indicative ranges. It does not account for parallel work, staffing, delivery dates, or production readiness.</p></section><section className="rounded-3xl border border-white/8 bg-[#091423] p-5"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-violet-300/10 text-violet-100"><CheckCircle2 className="h-4 w-4" /></span><div><p className="text-sm font-medium text-slate-100">Decision rule</p><p className="text-xs text-slate-500">What changes first?</p></div></div><div className="mt-6 space-y-4"><Rule number="1" text="Remove known classical weaknesses that create immediate exposure." /><Rule number="2" text="Upgrade shared dependencies that unlock several connected services." /><Rule number="3" text="Introduce hybrid PQC paths at long-lived, sensitive trust boundaries." /></div><div className="mt-6 rounded-2xl border border-cyan-200/10 bg-cyan-300/[0.04] p-4"><p className="flex items-center gap-2 text-xs font-medium text-cyan-100"><Timer className="h-4 w-4" />Planning posture</p><p className="mt-2 text-xs leading-5 text-slate-400">Wave estimates are indicative. Release gates should include interoperability, rollback, operational-owner, and evidence-verification checks.</p></div></section></aside></div></div>;
}
function RoadmapDetail({ icon: Icon, label, text }: { icon: typeof Boxes; label: string; text: string }) { return <div className="rounded-xl border border-white/7 bg-white/[0.025] p-3"><p className="flex items-center gap-1.5 text-[10px] font-semibold uppercase tracking-[0.14em] text-slate-600"><Icon className="h-3.5 w-3.5" />{label}</p><p className="mt-1.5 text-xs leading-5 text-slate-400">{text}</p></div>; }
function Rule({ number, text }: { number: string; text: string }) { return <div className="flex gap-3"><span className="grid h-6 w-6 shrink-0 place-items-center rounded-full bg-white/5 text-xs text-cyan-100">{number}</span><p className="pt-0.5 text-xs leading-5 text-slate-400">{text}</p></div>; }
