import { useEffect, useState } from "react";
import { ArrowLeft, ArrowRight, ExternalLink, FlaskConical, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { decodeFinding } from "@/lib/labEncoding";
import { buildScenarioFromFinding, labScenarios, type LabScenario } from "@/lib/labScenarios";
import { LabPipeline } from "@/lab/LabPipeline";
import { ApplyStage, DiscoveredStage, ProposedStage, TestStage, VerifyStage } from "@/lab/LabStages";

export function LabApp() {
  const [scenario, setScenario] = useState<LabScenario | null>(null);
  const [stage, setStage] = useState(1);
  const [unlocked, setUnlocked] = useState(1);
  useEffect(() => { const params = new URLSearchParams(window.location.search); const scenarioKey = params.get("scenario"); const hashFinding = window.location.hash.startsWith("#f=") ? decodeFinding(window.location.hash) : null; if (scenarioKey && labScenarios[scenarioKey]) setScenario(labScenarios[scenarioKey]); else if (hashFinding) setScenario(buildScenarioFromFinding(hashFinding)); }, []);
  const advance = () => { const next = Math.min(5, stage + 1); setUnlocked(current => Math.max(current, next)); setStage(next); };
  const close = () => { window.close(); window.setTimeout(() => { if (!window.closed) window.location.href = "/"; }, 120); };
  if (!scenario) return <main className="grid min-h-screen place-items-center bg-[#06101c] p-6 text-slate-100"><section className="max-w-md rounded-3xl border border-white/[0.08] bg-[#081321] p-6 text-center"><FlaskConical className="mx-auto h-8 w-8 text-cyan-100" /><h1 className="mt-4 font-display text-2xl font-semibold">Remediation Lab needs a scenario</h1><p className="mt-3 text-sm leading-6 text-slate-400">Launch the Lab from ECDAT, or use a supported `?scenario=` key. URL context is validated before display.</p><Button onClick={() => window.location.href = "/"} className="mt-5 bg-cyan-200 text-[#072033] hover:bg-cyan-100">Return to ECDAT</Button></section></main>;
  return <main className="min-h-screen bg-[radial-gradient(circle_at_top_right,rgba(34,211,238,.08),transparent_30%),#06101c] p-4 text-slate-100 md:p-8"><div className="mx-auto max-w-[1400px] space-y-6"><header className="flex flex-wrap items-center justify-between gap-4 border-b border-white/[0.08] pb-5"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-cyan-300/10 text-cyan-100"><FlaskConical className="h-5 w-5" /></span><div><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-cyan-100/70">Standalone local simulation</p><h1 className="font-display text-2xl font-semibold text-white">ECDAT Remediation Lab</h1></div></div><Button variant="outline" onClick={close} className="border-white/10 bg-white/[0.025] text-slate-300"><X className="h-4 w-4" />Close Lab</Button></header><section className="rounded-3xl border border-white/[0.08] bg-[#081321]/80 p-5"><p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-slate-500">Working scenario</p><div className="mt-2 flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-display text-xl font-semibold text-white">{scenario.title}</h2><p className="mt-1 text-sm text-slate-500">{scenario.finding.sourceLocation} · {scenario.finding.confidence}% retained context confidence</p></div><span className="inline-flex items-center gap-1.5 text-xs text-cyan-100"><ExternalLink className="h-3.5 w-3.5" />Independent browser tab</span></div></section><LabPipeline stage={stage} unlocked={unlocked} onSelect={setStage} />{stage === 1 ? <DiscoveredStage scenario={scenario} /> : null}{stage === 2 ? <ProposedStage scenario={scenario} /> : null}{stage === 3 ? <ApplyStage scenario={scenario} onApplied={() => setUnlocked(current => Math.max(current, 4))} /> : null}{stage === 4 ? <TestStage scenario={scenario} onTested={() => setUnlocked(5)} /> : null}{stage === 5 ? <VerifyStage scenario={scenario} /> : null}<footer className="flex flex-wrap items-center justify-between gap-3 border-t border-white/[0.08] pt-5"><p className="text-xs text-slate-600">ECDAT Remediation Lab is a local simulation. It does not modify a repository, dependency, configuration, or production state.</p><div className="flex gap-2">{stage > 1 ? <Button variant="outline" onClick={() => setStage(s => Math.max(1, s - 1))} className="border-white/10 bg-white/[0.025] text-slate-300"><ArrowLeft className="h-4 w-4" />Back</Button> : null}{stage < 5 ? <Button onClick={advance} className="bg-cyan-200 text-[#072033] hover:bg-cyan-100">Continue<ArrowRight className="h-4 w-4" /></Button> : null}</div></footer></div></main>;
}
