import { useState } from "react";
import { AlertTriangle, CheckCircle2, ClipboardCheck, Code2, FileSearch, FlaskConical, ShieldCheck, Timer } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import type { LabScenario } from "@/lib/labScenarios";
import { RemediationLab } from "@/lab/RemediationLab";

const Metric = ({ label, value }: { label: string; value: string }) => <div className="rounded-xl border border-white/[0.08] bg-white/[0.025] p-3"><p className="text-[10px] font-semibold uppercase tracking-[0.12em] text-slate-500">{label}</p><p className="mt-1.5 break-words text-sm text-slate-200">{value}</p></div>;
const Note = ({ children }: { children: React.ReactNode }) => <p className="rounded-xl border border-amber-300/12 bg-amber-300/[0.04] p-3 text-xs leading-5 text-amber-100"><AlertTriangle className="mr-1 inline h-3.5 w-3.5" />{children}</p>;

export function DiscoveredStage({ scenario }: { scenario: LabScenario }) { const finding = scenario.finding; return <section className="grid gap-5 lg:grid-cols-[1.05fr_.95fr]"><article className="rounded-3xl border border-white/[0.08] bg-[#081321] p-5"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-rose-300/10 text-rose-100"><FileSearch className="h-5 w-5" /></span><div><p className="text-[10px] font-semibold uppercase tracking-[0.15em] text-rose-100/70">Observed finding</p><h2 className="font-display text-2xl font-semibold text-white">{scenario.title}</h2></div></div><pre className="mt-5 overflow-x-auto rounded-2xl border border-white/[0.08] bg-[#06101c] p-4 font-mono text-xs leading-6 text-slate-300">{scenario.observedCode}</pre><Note>This standalone lab receives a compact finding context only. It does not read, clone, or modify a repository.</Note></article><article className="rounded-3xl border border-white/[0.08] bg-[#081321] p-5"><h3 className="font-display text-lg font-semibold text-white">Evidence context</h3><div className="mt-4 grid gap-3 sm:grid-cols-2"><Metric label="Risk" value={finding.riskLevel} /><Metric label="Confidence" value={`${finding.confidence}%`} /><Metric label="Library" value={finding.library} /><Metric label="Source" value={finding.sourceLocation} /><Metric label="Data lifetime" value={`${finding.dataLifetimeYears} years`} /><Metric label="Migration window" value={`${finding.migrationMonths} months`} /></div><div className="mt-5 flex flex-wrap gap-2"><Badge className="border border-white/10 bg-white/[0.04] text-slate-200">{finding.quantumVulnerable ? "Quantum-vulnerable" : "Quantum state monitored"}</Badge><Badge className="border border-white/10 bg-white/[0.04] text-slate-200">{finding.hndlExposure ? "Potential HNDL" : "No HNDL qualifier"}</Badge></div></article></section>; }

export function ProposedStage({ scenario }: { scenario: LabScenario }) { return <section className="grid gap-5 lg:grid-cols-3"><article className="rounded-3xl border border-white/[0.08] bg-[#081321] p-5"><p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-slate-500">Current observed state</p><p className="mt-4 font-mono text-xl text-rose-100">{scenario.finding.algorithm}</p><p className="mt-2 text-sm text-slate-400">{scenario.finding.cryptoRole} · {scenario.finding.library}</p></article><article className="rounded-3xl border border-cyan-200/18 bg-cyan-300/[0.05] p-5"><p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-cyan-100/70">Generated target path</p><p className="mt-4 font-mono text-xl text-cyan-100">{scenario.candidate}</p><p className="mt-2 text-sm leading-6 text-slate-400">{scenario.rationale}</p></article><article className="rounded-3xl border border-white/[0.08] bg-[#081321] p-5"><p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-slate-500">Planning impact</p><div className="mt-4 space-y-3"><Metric label="Compatibility" value={scenario.compatibility} /><Metric label="Indicative effort" value={scenario.effort} /><Metric label="Latency" value={scenario.latency} /></div></article><p className="lg:col-span-3 rounded-xl border border-amber-300/12 bg-amber-300/[0.04] p-3 text-xs leading-5 text-amber-100">This candidate is a simulated remediation proposal. Compatibility, effort, and performance require validation in an approved delivery environment.</p></section>; }

export function ApplyStage({ scenario, onApplied }: { scenario: LabScenario; onApplied: () => void }) { const [applied, setApplied] = useState(false); const apply = () => { setApplied(true); onApplied(); }; return <section className="rounded-3xl border border-white/[0.08] bg-[#081321] p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-slate-500">Simulated change set</p><h2 className="mt-1 font-display text-2xl font-semibold text-white">Proposed configuration diff</h2></div><Button onClick={apply} disabled={applied} className="bg-cyan-200 text-[#072033] hover:bg-cyan-100"><Code2 className="h-4 w-4" />{applied ? "Simulated change recorded" : "Record simulated application"}</Button></div><div className="mt-5 overflow-hidden rounded-2xl border border-white/[0.08] bg-[#06101c] font-mono text-xs leading-6">{scenario.diff.map(line => <div key={`${line.line}-${line.content}`} className={`grid grid-cols-[44px_1fr] gap-3 px-4 py-1 ${line.type === "add" ? "bg-emerald-300/[0.08] text-emerald-100" : line.type === "remove" ? "bg-rose-300/[0.08] text-rose-100" : "text-slate-400"}`}><span className="text-slate-600">{line.line}</span><span>{line.type === "add" ? "+ " : line.type === "remove" ? "− " : "  "}{line.content}</span></div>)}</div><Note>No repository, dependency, configuration, or production state is altered by this standalone simulation.</Note></section>; }

export function TestStage({ scenario, onTested }: { scenario: LabScenario; onTested: () => void }) { const [tested, setTested] = useState(false); const run = () => { setTested(true); window.setTimeout(onTested, 300); }; return <section className="rounded-3xl border border-white/[0.08] bg-[#081321] p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-slate-500">Simulated verification console</p><h2 className="mt-1 font-display text-2xl font-semibold text-white">Test the proposed path</h2></div><Button onClick={run} disabled={tested} className="bg-cyan-200 text-[#072033] hover:bg-cyan-100"><FlaskConical className="h-4 w-4" />{tested ? "Simulated checks recorded" : "Run simulated checks"}</Button></div><div className="mt-5 space-y-2">{scenario.testNames.map((name, index) => <div key={name} className="flex items-center justify-between rounded-xl border border-white/[0.08] bg-white/[0.02] p-3"><span className="flex items-center gap-3 text-sm text-slate-200">{tested ? <CheckCircle2 className="h-4 w-4 text-emerald-100" /> : <Timer className="h-4 w-4 text-slate-600" />}{name}</span><span className={tested ? "text-xs text-emerald-100" : "text-xs text-slate-600"}>{tested ? `simulated pass · ${(0.7 + index * 0.3).toFixed(1)}s` : "waiting"}</span></div>)}</div><Note>Results are intentionally simulated for the demo. They are not evidence that a production build, integration suite, cryptographic validation, or rescan passed.</Note></section>; }

export function VerifyStage({ scenario }: { scenario: LabScenario }) { return <section className="space-y-5"><div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><article className="rounded-3xl border border-emerald-300/18 bg-emerald-300/[0.05] p-5"><ShieldCheck className="h-8 w-8 text-emerald-100" /><p className="mt-5 text-[10px] font-semibold uppercase tracking-[0.14em] text-emerald-100/70">Simulation complete</p><h2 className="mt-1 font-display text-2xl font-semibold text-white">Ready for a validated change process</h2><p className="mt-3 text-sm leading-6 text-slate-400">The lab captured a proposed path and simulated checks. A real remediation requires governed approval, controlled application, validation, and a rescan.</p></article><article className="rounded-3xl border border-white/[0.08] bg-[#081321] p-5"><h3 className="font-display text-lg font-semibold text-white">Observed versus projected target</h3><div className="mt-4 grid gap-3 sm:grid-cols-2"><Metric label="Observed algorithm" value={scenario.finding.algorithm} /><Metric label="Projected candidate" value={scenario.candidate} /><Metric label="Observed quantum state" value={scenario.finding.quantumVulnerable ? "Vulnerable" : "Monitored"} /><Metric label="Projected posture" value="Requires validated scenario and rescan" /></div><p className="mt-5 rounded-xl border border-amber-300/12 bg-amber-300/[0.04] p-3 text-xs leading-5 text-amber-100"><ClipboardCheck className="mr-1 inline h-3.5 w-3.5" />No risk reduction, verified remediation, or production status is claimed by this standalone Lab.</p></article></div><RemediationLab /></section>; }
