import { Cell, Pie, PieChart } from "recharts";
import { ChartContainer, type ChartConfig } from "@/components/ui/chart";

const riskColors: Record<string, string> = { Critical: "#ff0003", High: "#ff8f3c", Medium: "#fdc448", Low: "#3eb75e" };
const exposureColors: Record<string, string> = { "Quantum-vulnerable": "#ff0003", "Legacy / monitor": "#ff8f3c", "Lower quantum exposure": "#3eb75e" };
const riskConfig = Object.fromEntries(Object.entries(riskColors).map(([key, color]) => [key, { label: key, color }])) satisfies ChartConfig;
const exposureConfig = Object.fromEntries(Object.entries(exposureColors).map(([key, color]) => [key, { label: key, color }])) satisfies ChartConfig;

function Donut({ data, centerTop, centerBottom, config }: { data: Array<{ label: string; count: number; color: string }>; centerTop: string; centerBottom: string; config: ChartConfig }) {
  const visible = data.some(item => item.count > 0) ? data : [{ label: "No data", count: 1, color: "rgba(255,255,255,0.08)" }];
  return <div className="relative mx-auto h-44 w-44 shrink-0"><ChartContainer config={config} className="h-full w-full !aspect-square"><PieChart><Pie data={visible} dataKey="count" nameKey="label" innerRadius="62%" outerRadius="92%" paddingAngle={visible.length > 1 ? 3 : 0} stroke="none">{visible.map(item => <Cell key={item.label} fill={item.color} />)}</Pie></PieChart></ChartContainer><div className="pointer-events-none absolute inset-0 grid place-items-center text-center"><div><p className="font-display text-3xl font-semibold tracking-[-0.05em] text-white">{centerTop}</p><p className="mt-1 text-[9px] font-semibold uppercase tracking-[0.14em] text-slate-500">{centerBottom}</p></div></div></div>;
}

export function RiskDistributionChart({ data, onSelect }: { data: Array<{ level: string; count: number }>; onSelect: (level: string) => void }) {
  const total = data.reduce((sum, item) => sum + item.count, 0);
  return <div className="flex flex-col gap-5 sm:flex-row sm:items-center"><Donut data={data.map(item => ({ label: item.level, count: item.count, color: riskColors[item.level] ?? "#64748b" }))} centerTop={String(total)} centerBottom="findings" config={riskConfig} /><div className="flex-1 space-y-2">{data.map(item => <button type="button" key={item.level} onClick={() => onSelect(item.level)} className="flex w-full items-center justify-between rounded-xl border border-transparent px-3 py-2 text-left transition hover:border-white/10 hover:bg-white/[0.035] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-200/60"><span className="flex items-center gap-2 text-xs text-slate-300"><span className="h-2.5 w-2.5 rounded-full" style={{ backgroundColor: riskColors[item.level] ?? "#64748b" }} />{item.level}</span><span className="text-xs font-semibold text-white">{item.count}<span className="ml-1 font-normal text-slate-500">findings</span></span></button>)}</div></div>;
}

export function QuantumExposureChart({ data, onSelectQuantum }: { data: { quantumVulnerable: number; legacyMargin: number; lowerQuantumExposure: number; exposedPercentage: number }; onSelectQuantum: () => void }) {
  const rows = [{ label: "Quantum-vulnerable", count: data.quantumVulnerable, color: exposureColors["Quantum-vulnerable"] }, { label: "Legacy / monitor", count: data.legacyMargin, color: exposureColors["Legacy / monitor"] }, { label: "Lower quantum exposure", count: data.lowerQuantumExposure, color: exposureColors["Lower quantum exposure"] }];
  return <div className="flex flex-col gap-5 sm:flex-row sm:items-center"><Donut data={rows} centerTop={`${data.exposedPercentage}%`} centerBottom="exposed" config={exposureConfig} /><div className="flex-1 space-y-2">{rows.map(item => <button type="button" key={item.label} onClick={item.label === "Quantum-vulnerable" ? onSelectQuantum : undefined} className={`flex w-full items-center justify-between rounded-xl px-3 py-2 text-left ${item.label === "Quantum-vulnerable" ? "transition hover:bg-white/[0.035] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-200/60" : "cursor-default"}`}><span className="flex items-center gap-2 text-xs text-slate-300"><span className="h-2.5 w-2.5 rounded-full" style={{ backgroundColor: item.color }} />{item.label}</span><span className="text-xs font-semibold text-white">{item.count}</span></button>)}<p className="px-3 pt-1 text-[10px] leading-4 text-slate-500">Exposure groups describe observed finding states; they do not certify PQC readiness.</p></div></div>;
}

export function AlgorithmDistribution({ data, onSelect }: { data: Array<{ algorithm: string; count: number; percentage: number }>; onSelect: (algorithm: string) => void }) {
  if (!data.length) return <p className="rounded-2xl border border-dashed border-white/10 p-5 text-sm text-slate-500">No observed algorithms are available for this assessment.</p>;
  return <div className="space-y-3">{data.map(item => <button type="button" key={item.algorithm} onClick={() => onSelect(item.algorithm)} className="group grid w-full grid-cols-[minmax(0,1fr)_auto] gap-x-4 rounded-xl px-2 py-1 text-left transition hover:bg-white/[0.035] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-orange-400/60"><span className="min-w-0"><span className="flex items-baseline justify-between gap-3"><span className="truncate text-sm font-medium text-slate-200">{item.algorithm}</span><span className="text-xs text-slate-500">{item.percentage}%</span></span><span className="mt-2 block h-1.5 overflow-hidden rounded-full bg-white/[0.06]"><span className="block h-full rounded-full bg-gradient-to-r from-[#fc4c1f] to-[#fdc448] transition group-hover:brightness-125" style={{ width: `${Math.max(item.percentage, 5)}%` }} /></span></span><span className="self-center text-sm font-semibold text-white">{item.count}</span></button>)}</div>;
}
