import { AlertTriangle, ArrowDown, ArrowUp, ExternalLink } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { riskDot, riskTone } from "@/lib/ecdatUi";
import { inventoryColumns, type InventoryColumnKey, type InventoryFinding, type InventorySort, type InventorySortKey } from "@/lib/inventoryUtils";

type Props = { findings: InventoryFinding[]; columns: InventoryColumnKey[]; sorting: InventorySort[]; selected?: string | null; onSort: (key: InventorySortKey, append: boolean) => void; onSelect: (findingKey: string) => void; onMove: (findingKey: string, direction: 1 | -1) => void };

export function InventoryTable({ findings, columns, sorting, selected, onSort, onSelect, onMove }: Props) {
  if (!findings.length) return null;
  return <><div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[1620px] text-left"><thead className="sticky top-0 z-10 bg-[#0d1a2a] text-[10px] uppercase tracking-[0.14em] text-slate-500"><tr>{columns.map(column => <HeaderCell key={column} column={column} sorting={sorting} onSort={onSort} />)}</tr></thead><tbody>{findings.map((finding, index) => <tr key={finding.findingKey} id={`finding-${finding.findingKey}`} tabIndex={0} role="button" aria-label={`View evidence for ${finding.assetName}`} onClick={() => onSelect(finding.findingKey)} onKeyDown={event => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); onSelect(finding.findingKey); } if (event.key === "ArrowDown" || event.key === "ArrowUp") { event.preventDefault(); const next = findings[index + (event.key === "ArrowDown" ? 1 : -1)]; if (next) { onMove(next.findingKey, event.key === "ArrowDown" ? 1 : -1); requestAnimationFrame(() => document.getElementById(`finding-${next.findingKey}`)?.focus()); } } }} className={`cursor-pointer border-b border-white/[0.05] transition hover:bg-white/[0.025] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-cyan-200/60 ${selected === finding.findingKey ? "border-l-2 border-l-cyan-300 bg-cyan-300/[0.06]" : ""}`}>{columns.map(column => <td key={column} className="px-3 py-3.5 align-middle">{renderCell(column, finding)}</td>)}</tr>)}</tbody></table></div><div className="space-y-3 md:hidden">{findings.map(finding => <button type="button" key={finding.findingKey} onClick={() => onSelect(finding.findingKey)} className={`w-full rounded-2xl border p-4 text-left transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-200/60 ${selected === finding.findingKey ? "border-cyan-200/35 bg-cyan-300/[0.06]" : "border-white/[0.08] bg-white/[0.02] hover:bg-white/[0.04]"}`}><div className="flex items-start justify-between gap-3"><span className="min-w-0"><span className="block truncate font-mono text-sm font-medium text-slate-100">{finding.assetName}</span><span className="mt-1 block text-xs text-slate-500">{finding.assetType} · {finding.cryptoRole}</span></span><RiskBadge finding={finding} /></div><div className="mt-4 grid grid-cols-2 gap-3 text-xs"><Cell label="Algorithm" value={finding.algorithm} mono /><Cell label="Quantum" value={finding.quantumVulnerable ? "Vulnerable" : finding.quantumRisk} /><Cell label="Environment" value={finding.environment} /><Cell label="Confidence" value={`${finding.confidence}%`} /></div></button>)}</div></>;
}

function HeaderCell({ column, sorting, onSort }: { column: InventoryColumnKey; sorting: InventorySort[]; onSort: (key: InventorySortKey, append: boolean) => void }) { const definition = inventoryColumns.find(item => item.key === column)!; const active = sorting.find(item => item.key === column); return <th className="px-3 py-3 font-medium">{definition.sortable ? <button type="button" onClick={event => onSort(column as InventorySortKey, event.shiftKey)} className={`inline-flex items-center gap-1 whitespace-nowrap ${active ? "text-cyan-100" : "hover:text-slate-300"}`}>{definition.label}{active?.direction === "asc" ? <ArrowUp className="h-3 w-3" /> : active?.direction === "desc" ? <ArrowDown className="h-3 w-3" /> : null}</button> : definition.label}</th>; }
function renderCell(column: InventoryColumnKey, finding: InventoryFinding) { if (column === "risk") return <RiskBadge finding={finding} />; if (column === "assetName") return <span className="block max-w-[190px] truncate font-mono text-xs font-medium text-slate-100">{finding.assetName}</span>; if (column === "algorithm") return <span className="inline-flex items-center gap-1 font-mono text-xs text-slate-200">{finding.quantumVulnerable ? <AlertTriangle className="h-3.5 w-3.5 text-rose-300" /> : null}{finding.algorithm}</span>; if (column === "confidence") return <span className="block min-w-20"><span className="flex justify-between text-xs text-slate-300"><span>{finding.confidence}%</span></span><span className="mt-1.5 block h-1.5 overflow-hidden rounded-full bg-white/[0.06]"><span className={`block h-full rounded-full ${finding.confidence > 80 ? "bg-emerald-400" : finding.confidence >= 50 ? "bg-amber-300" : "bg-rose-400"}`} style={{ width: `${finding.confidence}%` }} /></span></span>; if (column === "evidence") return <span title={finding.evidence || finding.provenance} className="inline-flex text-cyan-100"><ExternalLink className="h-4 w-4" /><span className="sr-only">View evidence description</span></span>; const value = finding[column]; return <span className={`block max-w-[180px] truncate text-xs text-slate-300 ${column === "sourceLocation" || column === "version" ? "font-mono" : ""}`}>{value || "—"}</span>; }
function RiskBadge({ finding }: { finding: InventoryFinding }) { return <Badge variant="outline" className={`gap-1.5 border-0 px-2 py-1 text-[10px] ring-1 ${riskTone[finding.riskLevel]}`}><span className={`h-1.5 w-1.5 rounded-full ${riskDot[finding.riskLevel]}`} />{finding.riskLevel}</Badge>; }
function Cell({ label, value, mono = false }: { label: string; value: string; mono?: boolean }) { return <span><span className="block text-[9px] font-semibold uppercase tracking-[0.12em] text-slate-600">{label}</span><span className={`mt-1 block truncate text-slate-300 ${mono ? "font-mono" : ""}`}>{value}</span></span>; }
