import { X } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import type { MigrationItem } from "@/lib/migrationStore";

const columns = [
  { key: "P1", label: "Immediate", tone: "border-rose-200/20 bg-rose-300/[0.05] text-rose-100" },
  { key: "P2", label: "High priority", tone: "border-amber-200/20 bg-amber-300/[0.05] text-amber-100" },
  { key: "P3", label: "Medium priority", tone: "border-cyan-200/20 bg-cyan-300/[0.05] text-cyan-100" },
  { key: "P4", label: "Long term", tone: "border-emerald-200/20 bg-emerald-300/[0.05] text-emerald-100" },
];

export function KanbanBoard({ items, onStatusChange, onRemove, onCardClick }: { items: MigrationItem[]; onStatusChange: (findingKey: string) => void; onRemove: (findingKey: string) => void; onCardClick: (findingKey: string) => void }) {
  return <section className="rounded-3xl border border-white/8 bg-[#091423] p-5 md:p-6"><div className="flex flex-col gap-2 md:flex-row md:items-end md:justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-cyan-200/60">Execution board</p><h2 className="mt-2 font-display text-xl font-semibold tracking-[-0.03em] text-white">Migration kanban</h2></div><p className="text-xs leading-5 text-slate-500">Select a card to inspect the linked evidence and migration scenario. Click its status to move through the local planning workflow.</p></div>{!items.length ? <div className="mt-5 rounded-2xl border border-dashed border-white/10 bg-white/[0.02] p-5 text-sm text-slate-500">No items yet. Add an evidence-backed recommendation from the table below to start a local migration plan.</div> : <div className="mt-5 grid gap-4 xl:grid-cols-4">{columns.map(column => { const columnItems = items.filter(item => item.priority.startsWith(column.key)); return <section key={column.key} className="min-h-48 rounded-2xl border border-white/8 bg-black/10 p-3"><div className="flex items-center justify-between gap-2"><Badge variant="outline" className={column.tone}>{column.label}</Badge><span className="text-xs text-slate-500">{columnItems.length}</span></div><div className="mt-3 space-y-3">{columnItems.length ? columnItems.map(item => <article key={item.findingKey} className="rounded-xl border border-white/8 bg-white/[0.025] p-3 shadow-sm"><button type="button" onClick={() => onCardClick(item.findingKey)} className="w-full text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-200/70"><p className="text-sm font-medium text-slate-100">{item.assetName}</p><p className="mt-1 text-xs leading-5 text-cyan-100">{item.algorithm} <span className="text-slate-500">→</span> {item.candidate}</p></button><div className="mt-3 flex items-center justify-between gap-2"><Badge variant="outline" className="border-white/10 text-[10px] text-slate-400">{item.complexity}</Badge><Button size="sm" variant="outline" onClick={() => onStatusChange(item.findingKey)} className="h-7 border-white/10 bg-white/[0.025] px-2 text-[10px] text-slate-300 hover:bg-cyan-300/[0.08]">{item.status}</Button></div><button type="button" onClick={() => { if (window.confirm(`Remove ${item.assetName} from the local migration plan?`)) onRemove(item.findingKey); }} className="mt-3 flex items-center gap-1 text-[10px] text-slate-500 transition hover:text-rose-200"><X className="h-3 w-3" />Remove</button></article>) : <p className="rounded-xl border border-dashed border-white/10 p-3 text-xs leading-5 text-slate-600">No {column.label.toLowerCase()} plan items.</p>}</div></section>; })}</div>}</section>;
}
