import { BadgeCheck, Gauge, Network, ShieldCheck, TimerReset } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import type { InventoryFinding } from "@/lib/inventoryUtils";
import type { MigrationDraft } from "@/lib/migrationStore";
import type { SpatialRecommendation } from "@/lib/spatialProjection";

export function MigrationSimulator({ finding, recommendation, blast, planned, onAdd }: { finding: InventoryFinding; recommendation?: SpatialRecommendation; blast: { summary: { servicesAndEndpoints: number; evidenceNodes: number; libraries: number } }; planned: boolean; onAdd: (item: MigrationDraft) => void }) {
  if (!recommendation) return <div className="rounded-2xl border border-dashed border-white/10 p-5 text-sm text-slate-500">No generated migration recommendation is available for this observed finding.</div>;
  const draft: MigrationDraft = { findingKey: finding.findingKey, assetName: finding.assetName, algorithm: finding.algorithm, candidate: recommendation.candidate, priority: `P${recommendation.priority}`, complexity: recommendation.indicativeEffort };
  return <div className="space-y-4"><div className="grid gap-3 sm:grid-cols-[1fr_auto_1fr]"><StateCard label="Current state" value={finding.algorithm} detail={`${finding.library ?? "Library not observed"}${finding.version ? ` ${finding.version}` : ""}`} /><div className="hidden self-center text-center text-cyan-100 sm:block">→</div><StateCard label="Recommended path" value={recommendation.candidate} detail="Generated candidate; validate in the target environment." tone="cyan" /></div><div className="rounded-2xl border border-white/8 bg-white/[0.025] p-4"><p className="flex items-center gap-2 text-xs font-medium text-slate-100"><BadgeCheck className="h-4 w-4 text-emerald-200" />Compatibility context</p><p className="mt-3 text-xs leading-5 text-slate-400">{recommendation.compatibility}</p></div><div className="grid gap-3 sm:grid-cols-2"><Detail icon={TimerReset} label="Indicative effort" value={recommendation.indicativeEffort} /><Detail icon={Gauge} label="Indicative latency" value={recommendation.indicativeLatency} /><Detail icon={ShieldCheck} label="Risk reduction target" value={`${finding.quantumRisk} → validate candidate deployment`} /><Detail icon={Network} label="Observed impact lens" value={`${blast.summary.servicesAndEndpoints} services/endpoints · ${blast.summary.evidenceNodes} entities`} /></div><div className="rounded-2xl border border-amber-200/10 bg-amber-300/[0.04] p-4 text-xs leading-5 text-amber-100">The target path is a generated recommendation, not a verified post-migration risk score. Relationship context is evidence-derived and is not runtime reachability or exploit evidence.</div>{planned ? <Badge variant="outline" className="border-emerald-200/20 bg-emerald-300/[0.06] text-emerald-100">Already in local migration plan</Badge> : <Button onClick={() => onAdd(draft)} className="w-full bg-cyan-200 text-[#072131] hover:bg-cyan-100">Add to plan</Button>}</div>;
}
function StateCard({ label, value, detail, tone = "slate" }: { label: string; value: string; detail: string; tone?: "slate" | "cyan" }) { return <div className={`rounded-2xl border p-4 ${tone === "cyan" ? "border-cyan-200/15 bg-cyan-300/[0.04]" : "border-white/8 bg-white/[0.025]"}`}><p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-slate-500">{label}</p><p className={`mt-2 break-words font-mono text-sm ${tone === "cyan" ? "text-cyan-100" : "text-slate-100"}`}>{value}</p><p className="mt-2 text-xs leading-5 text-slate-500">{detail}</p></div>; }
function Detail({ icon: Icon, label, value }: { icon: typeof Gauge; label: string; value: string }) { return <div className="rounded-xl border border-white/8 bg-white/[0.025] p-3"><p className="flex items-center gap-1.5 text-[10px] font-semibold uppercase tracking-[0.13em] text-slate-500"><Icon className="h-3.5 w-3.5 text-cyan-100" />{label}</p><p className="mt-2 text-xs leading-5 text-slate-300">{value}</p></div>; }
